runtime: nodejs10

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1

default_expiration: '30d'

handlers:
  - url: /static
    static_dir: build/static
    http_headers:
      Access-Control-Allow-Origin: https://portfolio1-290106.ts.r.appspot.com/
  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html
    expiration: '0s'
